name: temove_pro
description: Témove Pro - Application Chauffeurs
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  
  # Maps & Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^13.0.0
  
  # HTTP & API
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Date & Time
  intl: ^0.20.2
  
  # Icons
  flutter_svg: ^2.0.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets pour les icônes et images TéMove
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
